### PR TITLE
Add local image support

### PR DESCRIPTION
**Pull request by dcermak**
cc: @jlausuch  @grisu48

### CODE REVIEW

**Comment by grisu48** [comment]
Hi Dan! This is a nice internal implementation and a good idea. I'm missing the ability to configure a custom container without fiddling around in the Python scripts itself, is this still part of a future PR or am I simply overlooking it?

**Comment by dcermak** [comment]
@grisu48 This is so far only the implementation in the backend library, this does not touch BCI tests at all (yet). I am looking for feedback on the syntax &  usability before I start integrating this in BCI tests.

**Review by grisu48 — APPROVED** [review]
LGTM!

**Comment by grisu48** [comment]
> @grisu48 This is so far only the implementation in the backend library, this does not touch BCI tests at all (yet). I am looking for feedback on the syntax & usability before I start integrating this in BCI tests.

I see, thanks for the clarification

**Pull request merged**
