### PR TITLE
Use context managers & refactor volume handling

### PR DESCRIPTION
**Pull request by dcermak**
cc @dirkmueller @mloviska about the volume handling

### CODE REVIEW

**Comment by mloviska** [comment]
Kudos, looks very promising. Special thanks for the verbose docs!

**Comment by dirkmueller** [comment]
Is there still a way to create container volumes outside a context manager? it could be useful to have volumes persist accross multiple tests (with a fixed, static name) rather than having them created via a context manager.

**Comment by dcermak** [comment]
> Is there still a way to create container volumes outside a context manager? it could be useful to have volumes persist across multiple tests (with a fixed, static name) rather than having them created via a context manager.

That was never possible.

**Comment by dcermak** [comment]
> Is there still a way to create container volumes outside a context manager? it could be useful to have volumes persist accross multiple tests (with a fixed, static name) rather than having them created via a context manager.

I am actually not even sure if that is a good idea. A persistent volume really only makes sense if you access it read only, because you have more or less no way to run tests in a deterministic order (especially when running them in parallel via xdist). So let's say that volumes will be read only, well then you have to pre-fill them with data somehow which would require a ton more functionality for something that could be achieved via a read-only bind mount. @dirkmueller or do you see a specific use case for shared volumes that I'm missing here?

**Pull request merged**
