### PR TITLE
Fix version property

### PR DESCRIPTION
**Pull request by dcermak**
Thanks to @m-dati for finding out what the issue was!

### CODE REVIEW

**Review by grisu48 — COMMENTED** [review]
Looks like a complex fix, but so far all good. I think the `poetry.lock` is still accidentally here?

**Comment by dcermak** [comment]
@grisu48 I force pushed those changes away.

**Review by grisu48 — APPROVED** [review]
LGTM!

**Comment by grisu48** [comment]
The release of the current ruby BCI container is blocked, any reasons not to proceed and merge this fix?

**Comment by dcermak** [comment]
> The release of the current ruby BCI container is blocked, any reasons not to proceed and merge this fix?

One of the tests got stuck and auto-merge did nothing as a result. I have restarted the pipeline now.

**Pull request merged**
